services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    command: sh -c "uv run python3 -m app"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
